#!/usr/bin/env bash

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 2 ]
    then
        echo "I"
    elif [ $count -eq 4 ]
    then
        echo "Love"
    elif [ $count -eq 6 ]
    then
        echo "Programming"
    fi
        # echo "Best School"
        (( count++ ))
done